language: ruby
cache: bundler
bundler_args: "--without production development"
rvm:
- 2.1.5
env:
  global:
    secure: I1y+4gfoZ8IQvUOAj8PI+k4n7ko7lVa0uM/vA/U9Q0dEEnhmieVMUk90pWzHmfm8D3XGsJhmdPiY1LL7c1uVeLs2LgixiOJTXceyPEe5etP7vZidGsQBU7DIvYI/Un1r9vA0jXMvkrKIdoy7MUrkC8INMywCCXU9mM6myjoWnT8=
